ErrBadRequest and ErrTimeout should be considered as successful attempts
cep21/circuit pull request #99
Opened 2020-12-01 11:46 UTC by trungdq88

2020-12-01 12:02 UTC, trungdq88 commented on v3/circuit.go
> +	c.close(runFuncDoneTime, false)
`c.IsOpen()` is already checked inside `c.close()`

2020-12-01 21:52 UTC, cep21 commented
Thanks for the PR, but I believe best thing here is probably to update the documentation.  The terminology was borrowed from the original Java Hystrix implementation by netflix.  Here is their javadoc: https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/exception/HystrixBadRequestException.html

The idea of a bad request is that it's the fault of the user calling the circuit, rather than the circuit itself.  Since nothing inside the circuit is intended to execute, it's not right to think the circuit is healthy (since you never did the real work of the circuit).

We should probably update the docs to mention that bad requests are as though the circuit itself was never called when considering opening it or closing it.

2020-12-01 21:52 UTC, cep21 requested changes
Update docs instead I believe.

2020-12-02 01:33 UTC, trungdq88 commented
I see, thanks for the explanation. I was able to verify that this is indeed the Hystrix's default behavior with bad requests, which I didn't know earlier.

While I think this behavior is not particularly useful for services where 404 is a perfect healthy response, I respect that this library should follow Hystrix specs consistently.

I'll another way to work around this, maybe mapping 404 as a success response or something. Thanks for reviewing the PR, let's just close this for now.

2020-12-02 01:33 UTC, closed without merging